CREATE DATABASE AULA
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE AULA;
CREATE TABLE IF NOT EXISTS TBPRODUTO(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	descricao TEXT,
    qtd MEDIUMINT UNSIGNED,
    precoUnitario DECIMAL(7,2),
    precoVenda DECIMAL(7,2),
    lucro TINYINT,
    statusProduto ENUM('ESGOTADO','DISPONIVEL')
)DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS TBALUNO(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    matricula INT NOT NULL,
    nome VARCHAR(30) NOT NULL,
    sexo ENUM('F','M'),
    dtNasc DATE,
    dtInicioCurso DATE,
    curso VARCHAR(50),
    cpf VARCHAR(15),
    notaA1 DECIMAL(4,2) NOT NULL,
    notaA2 DECIMAL(4,2) NOT NULL,
    media DECIMAL(4,2)
)DEFAULT CHARSET=utf8;
ALTER TABLE TBPRODUTO MODIFY lucro DECIMAL(5,2);
ALTER TABLE TBALUNO MODIFY cpf VARCHAR(15) UNIQUE NOT NULL;
DESC TBPRODUTO;
DESC TBALUNO;
use cadastro;
select * from cursos;
select * from gafanhotos;